### PR TITLE
User session status split

### LINKED ISSUE #355: Performance degredation when user status has a large number of users
We've had a report that FPSci appears to slow down significantly when more than 50 users are listed in the user status (and config) file. Someone will need to investigate this problem.

As a work around, you can remove participants from the file who aren't needed.

### PR DESCRIPTION
**Pull request by bboudaoud-nv**
This branch splits the per-session written user status (sessions completed) from the remainder of the user status file. The new per-session status file format supports an iterative write approach and therefore serializes to disk faster. This file uses a CSV format with `user ID`, `session ID` formatting for each line. It is read in once from disk at startup to recover the user session status for all users.

The old user status file still contains the `currentUser` field (and potentially adding new users) which requires write-back when the user changes/is added but otherwise should be written far less frequently.

Custom session status log names can be specified using the new `completedLogFilename` configuration parameter in the top-level of the user status file.

Merging this branch closes #355

### CODE REVIEW

**Comment by bboudaoud-nv** [comment]
This might interact w/ #348, perhaps we should attempt a fix for that issue in this branch

**Comment by jspjutNV** [comment]
I checked out this branch and it fails to build. I'm not sure what's going on yet, but the error happens outside of the code from this PR, but doesn't happen on the master branch. I'm investigating.

**Comment by jspjutNV** [comment]
73f8b05 fixed the build error.

**Comment by jspjutNV** [comment]
There appears to be a remaining bug, or at least weird behavior if `allowRepeat` is on, and the user selects sessions out of order. We sort of cover this in the readme, and `allowRepeat` is intended to be only used when the user can't select session order, so I think we can consider this documented behavior. I'll clarify a little in the docs.

**Review by jspjutNV — APPROVED** [review]
I made some changes to docs and fixed the test case that was no longer testing everything. This appears to work in my tests, but we'll want to be aware that something may break and need fixing. This does break the current "create user" hack somewhat used by some experiments, so we will want to prioritize that fix for the next release.

**Pull request merged**
